// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRaZXP3Jl3hRYQnl5Mr460MTNZEeZTX6o',
    appId: '1:1014696265020:web:a4911996b6f259d858ca39',
    messagingSenderId: '1014696265020',
    projectId: 'real-estate-app-958c7',
    authDomain: 'real-estate-app-958c7.firebaseapp.com',
    storageBucket: 'real-estate-app-958c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0LAMmU0_p2XmfRauAaedmTX-oPXs19WY',
    appId: '1:1014696265020:android:908cc1f327cd13e758ca39',
    messagingSenderId: '1014696265020',
    projectId: 'real-estate-app-958c7',
    storageBucket: 'real-estate-app-958c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS6f0gN_y9jkx_TLuTCikCbNlv2Sq4a38',
    appId: '1:1014696265020:ios:47a98f588d704ae458ca39',
    messagingSenderId: '1014696265020',
    projectId: 'real-estate-app-958c7',
    storageBucket: 'real-estate-app-958c7.appspot.com',
    iosBundleId: 'com.example.realEstate',
  );
}
